Use an Arc Mutex to set the clock only once
thirtythreeforty/neolink pull request #69
Opened 2020-08-14 04:39 UTC by QuantumEntangledAndy

Here is an attempt at setting the clock only once per camera.

It is my first foray into cross thread locking in rust so I hope I got it right. I mostly just followed the [docs](https://doc.rust-lang.org/std/sync/struct.Mutex.html) on `Arc<Mutex>`.

It works by creating a `Arc<Mutex<bool>>` in the camera config (with serde=skip so that it cannot be set in the config file). I use try_lock() to attempt to lock it and if successful it goes on to set the time, if unable to lock it just skips the time setting code entirely.

closes #57

2020-09-13 07:06 UTC, thirtythreeforty commented
So the thing I don't like about this approach is it doesn't handle the following sequence:

- Camera boots, needs time
- Neolink connects
- Neolink sets time, once
- Camera loses power
- Neolink reconnects
- Camera does not get time set again

Instead, what if we designate one of the stream threads as the "management" thread, and it will always try to check to see if the time is set when it connects. That way, there's no race between threads, and you don't have to modify the camera config struct.

2020-09-13 07:09 UTC, thirtythreeforty requested changes
Try passing a new `manage: bool` argument to `camera_main()`. You can calculate it when you're setting up the camera threads based on if you're streaming HD/SD or just SD (just pick the first you come across or whatever's easiest). That way you don't need locks at all!

2020-09-13 09:37 UTC, QuantumEntangledAndy commented
Ok, less fun without the locks :p, but here what about this one :)

2020-09-16 13:34 UTC, thirtythreeforty approved these changes
Looks good! Yeah without locks it's less fun :)

2020-09-16 13:35 UTC, merged